In [2]:
# Create a random tensor with shape (7,7)

import torch

random_tensor = torch.rand(7,7)
random_tensor, random_tensor.shape

(tensor([[0.5372, 0.5476, 0.0111, 0.7776, 0.5060, 0.7077, 0.4092],
         [0.7828, 0.4208, 0.1148, 0.0018, 0.8521, 0.4051, 0.5355],
         [0.5175, 0.2403, 0.3506, 0.2896, 0.4035, 0.2405, 0.0091],
         [0.9628, 0.0222, 0.3102, 0.6626, 0.6782, 0.7000, 0.8207],
         [0.5379, 0.6848, 0.2911, 0.6821, 0.4427, 0.0047, 0.0915],
         [0.0803, 0.6284, 0.7690, 0.9819, 0.8898, 0.6089, 0.3958],
         [0.6686, 0.5476, 0.0288, 0.0673, 0.5501, 0.5114, 0.4349]]),
 torch.Size([7, 7]))

In [3]:
#Perform a matrix multiplication on the tensor from 2 with another
#random tensor with shape (1, 7) (hint: you may have to transpose the second tensor)

In [6]:
another_tensor = torch.rand(1,7)
another_tensor,another_tensor.shape

(tensor([[0.4567, 0.3866, 0.7882, 0.8157, 0.6266, 0.9783, 0.9567]]),
 torch.Size([1, 7]))

In [4]:
tensorResult1 = torch.matmul(random_tensor, another_tensor)
tensorResult1

RuntimeError: mat1 and mat2 shapes cannot be multiplied (7x7 and 1x7)

In [7]:
new_another = another_tensor.T
new_another, new_another.shape

(tensor([[0.4567],
         [0.3866],
         [0.7882],
         [0.8157],
         [0.6266],
         [0.9783],
         [0.9567]]),
 torch.Size([7, 1]))

In [9]:
tensorResult1 = torch.matmul(random_tensor, new_another)
tensorResult1, tensorResult1.shape

(tensor([[2.5009],
         [2.0547],
         [1.3387],
         [3.1284],
         [1.6658],
         [3.2186],
         [1.8558]]),
 torch.Size([7, 1]))

In [10]:
# Set random seed to 0 and do exercises 2 & 3 over again

import torch
random_seed = 0

torch.manual_seed(random_seed)
random_tensor = torch.rand(7,7)
random_tensor.shape

torch.manual_seed(random_seed)
another_tensor = torch.rand(1,7)
another_transpose = another_tensor.T


tensorResult1 = torch.matmul(random_tensor, another_transpose)
tensorResult1, tensorResult1.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

In [11]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
 # (hint: you'll need to look into the documentation for torch.cuda for this one).
# If there is, set the GPU random seed to 1234.

gpu_random_seed = 1234
gpu_random = torch.cuda.manual_seed(gpu_random_seed)
print(gpu_random)





None


In [17]:
#Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

import torch
torch.manual_seed(1234)

random_tensor = torch.rand(2,3)

another_tensor = torch.rand(2,3)

random_tensor.to(device='cuda'), another_tensor.to(device='cuda')

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [21]:
#Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors

matrix_mul_2 = torch.matmul(random_tensor, another_tensor.T)
matrix_mul_2

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

In [21]:
#Find the maximum and minimum values of the output of 7.
matrix_mul_2.min(), matrix_mul_2.max()

(tensor(0.0330), tensor(0.5584))

In [44]:
#Find the maximum and minimum index values of the output of 7.
matrix_mul_2.argmin(), matrix_mul_2.argmax()

(tensor(1), tensor(8))

In [45]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10).
# Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
import torch
set_seed = 7
torch.manual_seed(set_seed)
tensor_index = torch.rand(1, 1, 1, 10)

torch.manual_seed(set_seed)
tensor_to_squeeze = torch.rand(1, 1, 1, 10)


squeezed_tensor = tensor_to_squeeze.squeeze().shape
squeezed_tensor, tensor_index.shape

(torch.Size([10]), torch.Size([1, 1, 1, 10]))