In [1]:
# Create a random tensor with shape (7,7)

import torch

random_tensor = torch.rand(7,7)
random_tensor.shape

torch.Size([7, 7])

In [2]:
#Perform a matrix multiplication on the tensor from 2 with another
#random tensor with shape (1, 7) (hint: you may have to transpose the second tensor)

In [3]:
another_tensor = torch.rand(1,7)
another_tensor.shape

torch.Size([1, 7])

In [4]:
tensorResult1 = torch.matmul(random_tensor, another_tensor)
tensorResult1

RuntimeError: mat1 and mat2 shapes cannot be multiplied (7x7 and 1x7)

In [4]:
new_another = another_tensor.T
new_another.shape, another_tensor.shape

(torch.Size([7, 1]), torch.Size([1, 7]))

In [5]:
tensorResult1 = torch.matmul(random_tensor, new_another)
tensorResult1

tensor([[1.6361],
        [1.8431],
        [2.0125],
        [1.3104],
        [2.3438],
        [1.5589],
        [2.8539]])

In [2]:
# Set random seed to 0 and do exercises 2 & 3 over again

import torch
random_seed = 0

torch.manual_seed(random_seed)
random_tensor = torch.rand(7,7)
random_tensor.shape

torch.manual_seed(random_seed)
another_tensor = torch.rand(1,7)
another_transpose = another_tensor.T


tensorResult1 = torch.matmul(random_tensor, another_transpose)
tensorResult1

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [3]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
 # (hint: you'll need to look into the documentation for torch.cuda for this one).
# If there is, set the GPU random seed to 1234.

gpu_random_seed = 1234
gpu_random = torch.cuda.manual_seed(gpu_random_seed)
print(gpu_random)





None


In [16]:
#Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

import torch
random_seed = 1234

torch.manual_seed(random_seed)
random_tensor = torch.rand(2,3)
random_tensor.shape

torch.manual_seed(random_seed)
another_tensor = torch.rand(2,3)

random_tensor.to(device='cuda'), another_tensor.to(device='cuda')

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

In [17]:
#Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors

another_trans = another_tensor.T
another_trans.shape, random_tensor.shape
matrix_mul_2 = torch.matmul(another_trans, random_tensor)
matrix_mul_2

tensor([[0.1353, 0.0330, 0.2644],
        [0.0330, 0.1649, 0.1453],
        [0.2644, 0.1453, 0.5584]])

In [21]:
#Find the maximum and minimum values of the output of 7.
matrix_mul_2.min(), matrix_mul_2.max()

(tensor(0.0330), tensor(0.5584))

In [44]:
#Find the maximum and minimum index values of the output of 7.
matrix_mul_2.argmin(), matrix_mul_2.argmax()

(tensor(1), tensor(8))

In [45]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10).
# Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
import torch
set_seed = 7
torch.manual_seed(set_seed)
tensor_index = torch.rand(1, 1, 1, 10)

torch.manual_seed(set_seed)
tensor_to_squeeze = torch.rand(1, 1, 1, 10)


squeezed_tensor = tensor_to_squeeze.squeeze().shape
squeezed_tensor, tensor_index.shape

(torch.Size([10]), torch.Size([1, 1, 1, 10]))