In [ ]:
import torch
import pandas as pd
import numpy as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


In [ ]:
tensor1 = torch.matmul(torch.rand(3,2), torch.rand(2,3))
tensor1.shape

torch.Size([3, 3])

In [ ]:
tensA = torch.tensor([[1,2], [3,4], [5,6]])
tensB = torch.tensor([[7,10], [8,11], [9,12]])

In [ ]:
tensA.shape, tensA.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
torch.matmul(tensA, tensB)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
## Switching dimension of tensB with Transpose

In [ ]:
tensB, tensB.shape

In [ ]:
tensB.T, tensB.T.shape

In [ ]:
## After transposing tensB, the multiplication works as it now abides by the matrix mul rules
print(f"Original shapes (tensA and tensB): {tensA.shape, tensB.shape}")
print(f"\nNew shapes after transposing tensB: {tensA.shape, tensB.shape}")
print(f"\nAs the new inner dimensions match, we multiply {tensA.shape} @ {tensB.T.shape}")

print(f"\nNow we can multiply and the result is:")
result = torch.matmul(tensA, tensB.T)
print(result)

print(f"\nProduct shape: {result.shape}")

In [ ]:
import torch
x = torch.arange(1.,10.)
x, x.shape

In [ ]:
x.shape

In [ ]:
# torch.squeeze removes all single dimensions from a target sensor
xGetreshaped = x.reshape(1, 9)
xGetreshaped, xGetreshaped.shape

In [ ]:
 xGetreshaped.shape

In [ ]:
xGetreshaped.squeeze().shape

In [ ]:
y = xGetreshaped.squeeze().shape
y

In [ ]:
# Unsqueeze adds a single dimension to a target tensor at a specific dim
import torch
k = torch.arange(1.,10.)
k, k.shape

In [ ]:
kUns = k.unsqueeze(dim=0)
kUns, kUns.shape

In [ ]:
# torch.permute returns a view of the og input tensor
x_og = torch.rand(size=(224, 224, 3)) # height, width, color channels


In [ ]:
x_permuted = x_og.permute(2, 0, 1)

print(f"Prev shape: {x_og.shape}")
print(f"New shape: {x_permuted.shape}") # color chennels, height, width

In [ ]:
x_og[1, 1 , 1] = 12345

In [ ]:
print(f"Original tensor: {x_og[1, 1, 1]}")
print(f"Permuted tensor: {x_permuted[1, 1, 1]}")

In [ ]:
##Indexing (selecting data from tensors)

##Indexing wih PyTorch is similar to indexing with Numpy

In [ ]:
import torch
x = torch.arange(1,10).reshape(1, 3 , 3)
x, x.shape

In [ ]:
# Indexing on previous tensor dim=0
x[0]

In [ ]:
# Indexing on dim=1

In [ ]:
print(f"Format one: {x[0,0], x[0,1]}")
print(f"Format two: {x[0][0], x[0][1]}")

In [ ]:
# Indexing on dim=2

In [ ]:
print(f"Format one: {x[0,0,0], x[0,1,2]}")
print(f"Format two: {x[0][0][0], x[0][1][2]}")

In [ ]:
# Using ":" to select "all" of a target dimension
x[:,0], x[0,:], x[0,2,:]

In [ ]:
# get all values from 0 and 1 dimensions with index 2 of dim 2
x[:, :, 2]

In [ ]:
# get index 0 of dim 0, get all values from 1 dimensions with index 2 of dim 2
x[0, :, 2]

In [ ]:
# Index on x to return 9
x[0,2,2]

In [ ]:
# Index on x to return 3,6,9
x[:,:,2], x[0,:,2]

In [ ]:
## PyTorch tensor & NumPy
import torch
import numpy as np

#Numpys default datatype is float 64
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, array.dtype,  tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Making a numpy array of type float 32
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, array.dtype, tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [ ]:
array = array + 2
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#Tensor to Numpy array
tensor = torch.ones(7)
tensor_to_numpy = tensor.numpy()
tensor, tensor.dtype, tensor_to_numpy, tensor_to_numpy.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

In [ ]:
# checking if they share memory (if they both change when changes are made to either of them)
tensor = tensor + 1
tensor, tensor_to_numpy
# they do not share the same memory

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [17]:
# PyTorch Reproducibility(trying to take random out of random)
import torch
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(2,3)

print(f"Tensor A:\n {tensor_A}")
print(f"Tensor B:\n {tensor_B}")
print(f"Does Tensor A equal Tensor B?\n {tensor_A == tensor_B}")

Tensor A:
 tensor([[0.6885, 0.3822, 0.2774],
        [0.3116, 0.7652, 0.1018]])
Tensor B:
 tensor([[0.7637, 0.2185, 0.1398],
        [0.7369, 0.3644, 0.4194]])
Does Tensor A equal Tensor B?
 tensor([[False, False, False],
        [False, False, False]])


In [20]:
# Random but reproducible tensors
import torch

#Set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(2,3)

torch.manual_seed(RANDOM_SEED)
tensor_D = torch.rand(2,3)

print(f"Tensor C:\n {tensor_C}")
print(f"Tensor D:\n {tensor_D}")
print(f"Does Tensor C equal Tensor D?\n {tensor_C == tensor_D}")
# random seed only works for one block of code (if using a notebook)

Tensor C:
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
Tensor D:
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
Does Tensor C equal Tensor D?
 tensor([[True, True, True],
        [True, True, True]])


In [1]:
#Running tensors & pytorch objecrs on the GPUS (& making faster computations)

#### GO TO RUNTIME SETTINGS TO CHANGE TO THE FREE GPU
import torch
torch.cuda.is_available()

True

In [2]:
!nvidia-smi

# device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

Tue Jul 16 20:07:36 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

'cuda'

In [3]:
# Moving tensors to GPU (if available) Using a gpu results in faster computations


In [4]:
# Create a tensor (default on the CPU
tensor = torch.tensor([3, 2, 1], device='cpu')

# Tensor that is not on GPU
print(tensor, tensor.device)

tensor([3, 2, 1]) cpu


In [6]:
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([3, 2, 1], device='cuda:0')

In [12]:
# NumPy only works with the CPU
# Moving tensors back to CPU

# tensor_gpu.numpy() does not work, you must add cpu() before numpy

tensor_gpu.cpu().numpy()

array([3, 2, 1])

In [ ]:
########### Exercises and extra-curriculum